### ISSUE TITLE
Exposed API Key

### ISSUE THREAD

**Issue by erust1** [DIY-Machines/SmartChess#1]
Just came across this in your code. You might want to purge your Github repo of your Adafruit IO API key. I found it in the [receive-online.py](https://github.com/DIY-Machines/SmartChess/blob/main/RaspberryPiCode/receive-online.py) file. It's blurred within the writeup, so I just wanted to let you know it's there on the public repo.

**Comment by DIY-Machines** [comment]
Thanks for letting me know. I have disabled that key now and created myself some new (this time more private) ones.
